name: Frontend checks

on:
  workflow_call:
    inputs:
      working-directory:
        description: "Path to application relative to root, without trailing slash. Must contain a .nvmrc file specifying the required node version."
        type: string
        required: false
        default: "."
      format-check:
        description: "Enable to run `npm run format-check`. Before enabling this check, make sure you have set up the `format-check` script in package.json."
        type: boolean
        required: true
      lint-check:
        description: "Enable to run `npm run lint-check`. Before enabling this check, make sure you have set up the `lint-check` script in package.json."
        type: boolean
        required: true
      type-check:
        description: "Enable to run `npm run type-check`. Before enabling this check, make sure you have set up the `type-check` script in package.json."
        type: boolean
        required: true

jobs:
  frontend-checks:
    name: format · lint · type
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: ${{ inputs.working-directory }}/.nvmrc
          cache: npm
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run format-check
        if: ${{ !cancelled() && inputs.format-check }}
        run: npm run format-check

      - name: Run lint-check
        if: ${{ !cancelled() && inputs.lint-check }}
        run: npm run lint-check

      - name: Run type-check
        if: ${{ !cancelled() && inputs.type-check }}
        run: npm run type-check
