name: Release notification

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  slack-notification:
    name: Slack notification
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'released'
    steps:
      - name: Send notification
        uses: slackapi/slack-github-action@v3
        env:
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}
          REPO_NAME: ${{ github.event.repository.name }}
          RELEASE_NAME: ${{ github.event.release.name }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Ny release i ${{github.event.repository.name}}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "<${{ env.REPO_URL }}|${{ env.REPO_NAME }}>: ${{ env.RELEASE_NAME }} (<${{ env.REPO_URL }}/releases/tag/${{ env.RELEASE_TAG }}|#${{ env.RELEASE_TAG }}>)"
